# Gemini gets requirements and generates test cases and returns in JSON format
from langchain_google_genai import ChatGoogleGenerativeAI
from app.config import gemini_api_key
import json

def generate_test_cases(requirements: str, feature_name: str):
    llm = ChatGoogleGenerativeAI(
        api_key=gemini_api_key,
        model="gemini-3.5-flash-lite",
        temperature=0.1
    )

    prompt = f"""
    You are a QA Engineer. 
    
    Generate test cases for the following:
        FEATURE NAME:
        {feature_name}

        REQUIREMENT:
        {requirements}
    
    Test cases should cover the provided requirement.
    You may generate positive, negative, and edge cases ONLY when they directly relate to the provided requirement.
    Do NOT create test cases for behavior that is outside the provided requirement.
    Do NOT create opposite scenarios unless they are explicitly required by the requirement.
    Do NOT introduce additional functionality, conditions, or business rules that are not stated in the requirement.
    
    Return ONLY valid JSON.
    Do not add markdown.
    Do not add explanations before or after the JSON.

    The JSON must have exactly this structure:

    [
    {{
        "test_case_id": "TC_001",
        "test_case_name": {feature_name},
        "steps": [
          {{
            "step_number": 1,
            "test_step": "Verify ... - test case description",
            "expected_result": "..."
          }},
          {{
            "step_number": 2,
            "test_step": "Preconditions: ...",
            "expected_result": "..."
          }}
        ]
      }}
    ]

    IMPORTANT TEST CASE STRUCTURE:

    Each test case must contain sequential steps.
    
    STEP 1:
    The first step MUST start with "Verify".
    Step 1 describes ONLY what behavior or functionality the test case verifies.
    Example:
    "Verify user is prompted to re-enter password after session expiration"
    Do NOT perform any user action in Step 1.
    Do NOT describe Preconditions in Step 1.
    
    STEP 2:
    Step 2 MUST be the Preconditions step.
    The test_step value MUST start with:
    "Preconditions:"
    Step 2 must contain ALL conditions that must be established BEFORE the actual test actions start.
    Preconditions must describe the initial state of the user, application, account, or data.
    Preconditions can contain multiple conditions separated by new lines.
    Example:
    "Preconditions:
    User is registered.
    User is logged in.
    User has an active session.
    User account is linked with a store."
    
    IMPORTANT:
    Step 2 must NOT describe an action that the user performs during the test.
    Step 2 must NOT describe the expected behavior being tested.
    Step 2 must NOT describe the moment when the tested condition occurs.
    For example, this is WRONG:
    "User is logged into the application. Session timeout period is reached."
    Because "session timeout period is reached" is part of the test scenario, not an initial precondition.
    Instead:
    "Preconditions:
    User is logged into the application.
    User has an active session."
    
    STEP 3 AND FOLLOWING STEPS:
    Step 3 and all following steps must contain the actual actions performed during the test and the expected system behavior.
    Example:
    Step 3:
    Action: "Wait until the session timeout period is reached."
    Expected: "The session expires."
    
    Step 4:
    Action: "Attempt to perform an action requiring an active session."
    Expected: "The system requests the user to re-enter the password."
    
    Step 5:
    Action: "Enter the correct password."
    Expected: "The password is accepted."
    
    Step 6:
    Action: "Submit the password."
    Expected: "The user is successfully re-authenticated."
    
    GENERAL RULE:
    Think about the test case in this order:
    
    1. WHAT are we verifying?
    2. WHAT must already be true before the test starts?
    3. WHAT does the user/system do?
    4. WHAT should happen after each action?
    
    Never mix these four parts.
    
    Rules:
    - Every generated test case must directly verify the provided requirement.
    - Do not invent product functionality that is not described in the requirements.
    - Do not generate unrelated test cases.
    - Negative and edge cases are allowed only if they are directly related to the requirement.
    - Do not create tests for the absence of the required behavior unless the requirement explicitly requires it.
    - Do not test the opposite state unless it is explicitly described in the requirement.
    - Test Case ID can be generated by you.
    - Test Case Name must be exactly the feature name.
    - Do not modify the feature name.
    - Step numbers must start from 1 and be sequential.
    - Step 1 must always start with "Verify".
    - Step 1 must accurately describe the behavior being tested.
    - The verification statement in Step 1 must match the expected outcome of the test case.
    - Step 2 must always contain the Preconditions.
    - Step 3+ must contain actual test actions.
    - Steps must follow the logical execution order.
    - Expected results must be clear and concise.
    - Expected results must describe the observable result after the action and must not simply repeat the test step.
    - Generate enough test cases to cover the provided requirements.
    
    """

    response = llm.invoke(prompt)

    content = response.content

    if isinstance(content, list):
        content = "\n".join(
            item["text"]
            for item in content
            if item.get("type") == "text"
        )

    return json.loads(content)

# Gemini checks if requirements are covered by existing test cases
def check_test_coverage(requirement: str, fdd_content, existing_test_cases: str):
    llm = ChatGoogleGenerativeAI(
        api_key=gemini_api_key,
        model="gemini-3.5-flash-lite",
        temperature=0.1
    )

    prompt = f"""You are a QA test coverage analyzer.
    
    Your task is to determine whether the EXISTING TEST CASES
    already verify the REQUIREMENT.     

    REQUIREMENT:
    {requirement}
    
    FDD REQUIREMENTS:
    {fdd_content}

    EXISTING TEST CASES:
    {existing_test_cases}
    
    IMPORTANT:

    Compare the requirement with the CONTENT of ACTUAL TEST STEPS and EXPECTED RESULTS.

    Do NOT decide coverage based only on:
    - test case title
    - similar wording
    - similar feature name
    
    A requirement is COVERED only when an existing test case
    actually performs or verifies the behavior described by the requirement.
    
    For example:
    
    Requirement:
    "User can login using Phone Number."
    
    If existing test cases contain:
    - entering a phone number
    - entering a password
    - clicking Login
    - successfully logging in
    
    then the requirement IS COVERED.
    
    If existing test cases only contain:
    - opening Login page
    - entering Email
    
    then the requirement is NOT COVERED.
    
    Another example:
    
    Requirement:
    "User must re-enter password after session expires."
    
    The requirement is COVERED only if an existing test case
    explicitly verifies session expiration AND password re-entry.
    
    If the existing tests only verify normal login,
    the requirement is NOT COVERED.

    Rules:

    1. "covered": true only when the requirement is actually tested.
    2. "covered": false when the requirement is missing.
    3. Partial coverage must be false.
    4. Do not infer functionality that is not present in the test cases.
    5. Do not generate or modify test cases.
    6. Analyze the complete existing test cases.
    
    
    Return ONLY valid JSON.
    Do not add markdown.
    Do not add explanations.
    
    Return exactly:

    {{
        "covered": true,
        "reason": "Short explanation based on the existing test steps",
        "missing_requirements": []
    }}
    
    If "covered" is false, "missing_requirements" must contain
    the specific requirement parts that are NOT covered by the existing test cases.
    
    If "covered" is true, "missing_requirements" must be an empty list.

"""
    response = llm.invoke(prompt)

    content = response.content

    if isinstance(content, list): # if content is a list -> take only text
        content = "\n".join(
            item["text"]
            for item in content
            if item.get("type") == "text"
        )

    return json.loads(content) # return json -> to Python


def generate_missing_test_cases(requirements, existing_test_cases, feature_name):
    missing_test_cases = []

    for requirement in requirements:

        # 1. Check if requirement is covered
        coverage = check_test_coverage(
            requirement,
            existing_test_cases
        )

        print(f"\nRequirement: {requirement}")
        print(f"Coverage result: {coverage}")

        # 2. If covered - skip and go to the next
        if coverage["covered"]:
            print("SKIP: Requirement is already covered.")
            continue

        # 3. If not covered - generate new test cases
        print("GENERATE: Requirement is not covered.")

        new_test_cases = generate_test_cases(
            requirement,
            feature_name
        )

        missing_test_cases.extend(new_test_cases)

    return missing_test_cases